development:
  adapter: mysql2
  database: request_dev
  pool: 5
  username: root
  password:
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: request_production
  username: root
  password:
  encoding: utf8
